name: gumbi-dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python>3.9
  - pandas
  - numpy=1.20.3
  - scipy
  - seaborn
  - matplotlib
  - pymc3>=3.11.2
  - arviz>=0.11.2
  - uncertainties
  - ipympl
  - mkl
  - flake8
  - black
  - isort
  - pre-commit
  - commitizen
  - pytest
  - build
  - twine
  - pip
  - pip:
    - .
