name: gumbi-dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.10
  - pandas
  - numpy  #==1.25.2
  - scipy  #<1.13
  - seaborn
  - matplotlib
  - pymc>=5.10
  - botorch
  - arviz
  - uncertainties
  - ipympl
  - mkl
  #
  - jupytext
  - sphinx==6.2.1
  - sphinx_rtd_theme==1.2.0
  - pandoc
  - numpydoc
  - nbsphinx
  - ipython
  - ipympl
  - ipykernel
  - jupyter_client
  - flake8
  - black
  - isort
  - pre-commit
  - commitizen
  - pytest
  - build
  - twine
  - pip
  - pip:
    - -e ./
