name: gumbi-dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python>3.9
  - pandas
  - numpy
  - scipy
  - seaborn
  - matplotlib
  - pymc>=5.3.1
  - arviz
  - uncertainties
  - ipympl
  - mkl
  - jupytext
  - sphinx==6.2.1
  - sphinx_rtd_theme==1.2.0
  - pandoc
  - numpydoc
  - nbsphinx
  - ipython
  - jupyter_client
  - flake8
  - black
  - isort
  - pre-commit
  - commitizen
  - pytest
  - build
  - twine
  - pip
  - pip:
    - -e ./
