name: gumbi-dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python>3.7
  - pandas
  - numpy=1.19.2
  - scipy
  - seaborn
  - matplotlib
  - pymc3>=3.11.2
  - arviz>=0.11.2
  - uncertainties
  - ipympl
  - mkl
  - pip
  - pip:
    - .
