name: gumbi-dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python>3.9
  - pandas
  - numpy  #=1.19.2
  - scipy
  - seaborn
  - matplotlib
  - pymc
  - arviz
  - uncertainties
  - ipympl
  - mkl
  - flake8
  - black
  - isort
  - pre-commit
  - commitizen
  - pytest
  - build
  - twine
  - pip
  - pip:
    - -e ./
