name: gumbi
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.9
  - pandas
  - numpy  #=1.19.2
  - scipy
  - seaborn
  - matplotlib
  - pymc>=5.3.1
  - arviz
  - uncertainties
  - ipympl
  - mkl
  - pip
  - pip:
    - gumbi
