name: gumbi
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.10
  - pandas
  - numpy==1.25.2
  - scipy<1.13
  - seaborn
  - matplotlib
  - pymc>=5.10
  - arviz
  - uncertainties
  - ipympl
  - mkl
  - pip
  - pip:
    - gumbi
